"""
Simulation Log Analyzer and Visualizer

This script loads the static map (PGM) and the simulation log (JSON)
generated by the D* Lite simulation script (dstar_lite_simulation.py or similar)
and visualizes the robot's path overlaid on the map, highlighting key events.

How to Use:
1. Make sure 'simulation_map.pgm' and 'simulation_log.json' are in the
   same directory as this script, or provide the correct paths.
2. The 'MAP_METADATA' dictionary below has been updated based on the
   provided D* Lite script. Double-check these values if you modified
   the map saving logic in the original script.
3. Run this script using Python: python analyze_simulation.py
"""

import json
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import numpy as np
from typing import List, Dict, Any, Optional

MAP_FILENAME: str = "simulation_map.pgm"
LOG_FILENAME: str = "simulation_log.json"

MAP_METADATA: Dict[str, int] = {
    "world_x_min": 0,
    "world_y_min": 0,
    "map_width_pixels": 52,
    "map_height_pixels": 52
}

def load_log_data(filename: str) -> Optional[List[Dict[str, Any]]]:
    if not os.path.exists(filename):
        print(f"Error: Log file not found at '{filename}'")
        return None
    try:
        with open(filename, 'r') as f:
            log_data = json.load(f)
        print(f"Successfully loaded log data from '{filename}'. Found {len(log_data)} entries.")
        if not isinstance(log_data, list) or not log_data:
            print("Error: Log file does not contain a valid non-empty JSON list.")
            return None
        return log_data
    except json.JSONDecodeError:
        print(f"Error: Failed to decode JSON from '{filename}'. File might be corrupted.")
        return None
    except IOError as e:
        print(f"Error reading log file '{filename}': {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while loading log file: {e}")
        return None

def load_map_image(filename: str) -> Optional[np.ndarray]:
    if not os.path.exists(filename):
        print(f"Error: Map file not found at '{filename}'")
        return None
    try:
        map_img = mpimg.imread(filename)
        map_img = np.flipud(map_img)
        print(f"Successfully loaded and flipped map image from '{filename}'. Dimensions: {map_img.shape[1]}x{map_img.shape[0]} pixels.")
        if map_img.shape[1] != MAP_METADATA["map_width_pixels"] or map_img.shape[0] != MAP_METADATA["map_height_pixels"]:
            print(f"  Loaded Image Size: {map_img.shape[1]} (width) x {map_img.shape[0]} (height)")
            print(f"  Metadata Expected: {MAP_METADATA['map_width_pixels']} (width) x {MAP_METADATA['map_height_pixels']} (height)")
        return map_img
    except IOError as e:
        print(f"Error reading map file '{filename}': {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred while loading map file: {e}")
        return None

def visualize_simulation(log_data: List[Dict[str, Any]], map_img: Optional[np.ndarray]) -> None:
    if not log_data:
        print("No log data to visualize.")
        return
    try:
        poses = [entry.get('pose', {}) for entry in log_data]
        path_x = [p.get('x') for p in poses if p.get('x') is not None]
        path_y = [p.get('y') for p in poses if p.get('y') is not None]
        if not path_x or not path_y:
            print("Error: No valid pose data (x, y coordinates) found in the log.")
            return
        states = [entry.get('state', 'UNKNOWN') for entry in log_data]
    except Exception as e:
        print(f"Error processing log data for visualization: {e}")
        return
    plt.figure(figsize=(11, 10))
    map_plotted = False
    if map_img is not None:
        try:
            left = MAP_METADATA["world_x_min"] - 0.5
            right = MAP_METADATA["world_x_min"] + MAP_METADATA["map_width_pixels"] - 0.5
            bottom = MAP_METADATA["world_y_min"] - 0.5
            top = MAP_METADATA["world_y_min"] + MAP_METADATA["map_height_pixels"] - 0.5
            map_extent = [left, right, bottom, top]
            plt.imshow(map_img, cmap='gray', extent=map_extent, origin='lower', aspect='equal')
            map_plotted = True
            plt.xlim(left - 1, right + 1)
            plt.ylim(bottom - 1, top + 1)
        except Exception as e:
            print(f"Error displaying map image: {e}. Plotting path only.")
            plt.xlim(min(path_x) - 5, max(path_x) + 5)
            plt.ylim(min(path_y) - 5, max(path_y) + 5)
    else:
        plt.xlim(min(path_x) - 5, max(path_x) + 5)
        plt.ylim(min(path_y) - 5, max(path_y) + 5)
        print("Map image not loaded. Plotting path only.")
    plt.plot(path_x, path_y, marker='.', markersize=2, linestyle='-', color='red', label='Robot Path (from Log)', zorder=3)
    replanning_points = []
    for entry in log_data:
        state = entry.get('state', '')
        pose = entry.get('pose', {})
        x = pose.get('x')
        y = pose.get('y')
        if 'REPLANNING_DETECTED' in state and x is not None and y is not None:
            replanning_points.append((x, y))
    if replanning_points:
        replanning_x, replanning_y = zip(*replanning_points)
        plt.scatter(replanning_x, replanning_y, c='orange', s=60, label='Replanning Triggered', zorder=5, edgecolors='black')
        print(f"Highlighted {len(replanning_points)} replanning event(s).")
    else:
        print("No 'REPLANNING_DETECTED' states found in log.")
    plt.scatter(path_x[0], path_y[0], c='lime', s=100, marker='o', label='Start', zorder=4, edgecolors='black')
    plt.scatter(path_x[-1], path_y[-1], c='blue', s=100, marker='X', label='End', zorder=4, edgecolors='black')
    plt.xlabel('X Coordinate (World Frame)')
    plt.ylabel('Y Coordinate (World Frame)')
    plt.title('D* Lite Simulation Analysis: Robot Path on Map')
    plt.grid(True, linestyle='--', alpha=0.6)
    if map_plotted:
        plt.legend(loc='upper right', bbox_to_anchor=(1.25, 1.0))
        plt.tight_layout(rect=[0, 0, 0.85, 1])
    else:
        plt.legend(loc='best')
        plt.tight_layout()
    plt.gca().set_aspect('equal', adjustable='box')
    plt.show()

if __name__ == "__main__":
    print("--- Simulation Log Analyzer ---")
    simulation_log = load_log_data(LOG_FILENAME)
    static_map_image = load_map_image(MAP_FILENAME)
    if simulation_log:
        visualize_simulation(simulation_log, static_map_image)
    else:
        print("Exiting: Log data could not be loaded.")
    print("--- Analysis Complete ---")
